package com.rony.erpsoft.sales.controller;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.ExceptionConverter;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfWriter;
import com.rony.erpsoft.utils.AppUtil;

public class HeaderFooterHandler extends PdfPageEventHelper {
    Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
    Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Font.ITALIC);
    Image logo;

    // Optional: pass a logo image when constructing the handler
    public HeaderFooterHandler(Image logo) {
        this.logo = logo;
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        PdfPTable header = new PdfPTable(2);
        try {
            header.setWidths(new int[]{10, 90});
            header.setTotalWidth(document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin());
            header.setLockedWidth(true);
            header.getDefaultCell().setBorder(Rectangle.NO_BORDER);
            header.getDefaultCell().setVerticalAlignment(Element.ALIGN_MIDDLE);

            // Left: logo
            if (logo != null) {
                PdfPCell logoCell = new PdfPCell(logo, true);
                logoCell.setBorder(Rectangle.NO_BORDER);
                logoCell.setHorizontalAlignment(Element.ALIGN_LEFT);
                header.addCell(logoCell);
            } else {
                header.addCell(""); // empty cell if no logo
            }

            // Write header
            header.writeSelectedRows(0, -1, document.leftMargin(),
                    document.getPageSize().getHeight() - 10, writer.getDirectContent());

            // ---------------- FOOTER ----------------
            PdfPTable footer = new PdfPTable(2); // 2 columns: left text + right page number
            footer.setWidths(new int[]{70, 30}); // ratio of column widths
            footer.setTotalWidth(527);
            footer.setLockedWidth(true);
            footer.getDefaultCell().setFixedHeight(20);
            footer.getDefaultCell().setBorder(Rectangle.TOP);

            // Left side: generated text with current date
            String generatedText = "Generated by POS System on " +
                    AppUtil.getLocalDateTimeToString(java.time.LocalDateTime.now());
            PdfPCell leftCell = new PdfPCell(new Phrase(generatedText, footerFont));
            leftCell.setBorder(Rectangle.TOP);
            leftCell.setHorizontalAlignment(Element.ALIGN_LEFT);
            footer.addCell(leftCell);

            // Right side: page number
            PdfPCell rightCell = new PdfPCell(new Phrase("Page " + writer.getPageNumber(), footerFont));
            rightCell.setBorder(Rectangle.TOP);
            rightCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            footer.addCell(rightCell);

            // Write footer
            footer.writeSelectedRows(0, -1,
                document.leftMargin(),
                document.bottom() - 5,
                writer.getDirectContent());
        } catch (DocumentException de) {
            throw new ExceptionConverter(de);
        }
    }
}
