spring.mvc.view.prefix=/view/
spring.mvc.view.suffix=.jsp

app.name=ERP Software
app.full_name=
app.name.hash=d05aa0baa2b14a56615124311ea1a3e95a4138e3ee4ed822afb0acafa5391358

spring.jpa.show-sql =true
spring.jpa.hibernate.ddl-auto =update

spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=webapp/view/**

spring.profiles.active=dev

# Permanent folder outside Tomcat
app.upload.dir=/home/rony/Projects/data/uploads

# Increase file size limit if needed
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#Configure Hibernate to use your local timezone
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Dhaka